### ISSUE TITLE
Change sizes to uint64 and not int

### ISSUE THREAD

**Issue by newtoncorp** [klauspost/reedsolomon#9]
At least the Join method needs to be changed, it forbids us from having a reconstructed file with more than 2^31 bytes in it.

Are there hidden implications to this change or is this straightforward ? (Not counting the fact that file parts have to be < 2^31 bytes too)

**Comment by klauspost** [comment]
I cannot really change that, since it would break existing implementations.

Furthermore, there is no way for you to allocate enough memory to fill the shards, since the size of int on any platform is the same as the allowed memory allocation AFAIK . Meaning 32 bit machines cannot allocate more than 2GB of memory for a single process.

What operating system are you developing for?

It would be fairly trivial to write a streamed [Join](https://github.com/klauspost/reedsolomon/blob/master/reedsolomon.go#L496). A signature like this could be made:

```Go
func (r reedSolomon) JoinStream(dst io.Writer, shards []io.Reader, outSize int64) error
```
[int64 seems to be how the std library does it](https://golang.org/pkg/io/#Copy).

Would that be a solution for you?

**Comment by newtoncorp** [comment]
I am developing on Linux 64bits on machines that have plenty of ram.
I am fairly new to golang, is the int type in a 64bits environment equal to 64 or 32 bits ?

Other wise, the streamed join would be fine.

**Comment by klauspost** [comment]
On 64 bit machines, int is 64 bits. (63+sign)

While it isn't guaranteed, `int` is used for slice lookups, so in practice it always matches the memory size of the system. Otherwise, you could get into a sitation where you could only use a 2GB byte slice size on a 64 bit system, which isn't a useful limitation.

In hindsight, it would have been more obvious if the variable was int64, but it's too late to change that now.

Either way, a streaming interface would be a nice addition. I will see if I can make that!

**Comment by klauspost** [comment]
I started working on the streaming API, and got the first version in PR #10. 

You are welcome to track progress there.
